# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/AE_project/FPGA/AE_project/AE_project.srcs/sources_1/ip/ae_frame_bank_bram/ae_frame_bank_bram.xci
# IP: The module: 'ae_frame_bank_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/AE_project/FPGA/AE_project/AE_project.gen/sources_1/ip/ae_frame_bank_bram/ae_frame_bank_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ae_frame_bank_bram'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/AE_project/FPGA/AE_project/AE_project.srcs/sources_1/ip/ae_frame_bank_bram/ae_frame_bank_bram.xci
# IP: The module: 'ae_frame_bank_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/AE_project/FPGA/AE_project/AE_project.gen/sources_1/ip/ae_frame_bank_bram/ae_frame_bank_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ae_frame_bank_bram'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
