# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/AE_project/FPGA/AE_project/AE_project.srcs/sources_1/ip/ae_desc_fifo_ip/ae_desc_fifo_ip.xci
# IP: The module: 'ae_desc_fifo_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/AE_project/FPGA/AE_project/AE_project.gen/sources_1/ip/ae_desc_fifo_ip/ae_desc_fifo_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'ae_desc_fifo_ip'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/AE_project/FPGA/AE_project/AE_project.gen/sources_1/ip/ae_desc_fifo_ip/ae_desc_fifo_ip_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ae_desc_fifo_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/AE_project/FPGA/AE_project/AE_project.gen/sources_1/ip/ae_desc_fifo_ip/ae_desc_fifo_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ae_desc_fifo_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/AE_project/FPGA/AE_project/AE_project.srcs/sources_1/ip/ae_desc_fifo_ip/ae_desc_fifo_ip.xci
# IP: The module: 'ae_desc_fifo_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/AE_project/FPGA/AE_project/AE_project.gen/sources_1/ip/ae_desc_fifo_ip/ae_desc_fifo_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'ae_desc_fifo_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/AE_project/FPGA/AE_project/AE_project.gen/sources_1/ip/ae_desc_fifo_ip/ae_desc_fifo_ip_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ae_desc_fifo_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/AE_project/FPGA/AE_project/AE_project.gen/sources_1/ip/ae_desc_fifo_ip/ae_desc_fifo_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ae_desc_fifo_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
