# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/AE_project/FPGA/AE_project/AE_project.srcs/sources_1/ip/system_clk_module/system_clk_module.xci
# IP: The module: 'system_clk_module' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/AE_project/FPGA/AE_project/AE_project.gen/sources_1/ip/system_clk_module/system_clk_module_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_clk_module'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/AE_project/FPGA/AE_project/AE_project.gen/sources_1/ip/system_clk_module/system_clk_module.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_clk_module'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/AE_project/FPGA/AE_project/AE_project.gen/sources_1/ip/system_clk_module/system_clk_module_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_clk_module'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/AE_project/FPGA/AE_project/AE_project.srcs/sources_1/ip/system_clk_module/system_clk_module.xci
# IP: The module: 'system_clk_module' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/AE_project/FPGA/AE_project/AE_project.gen/sources_1/ip/system_clk_module/system_clk_module_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_clk_module'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/AE_project/FPGA/AE_project/AE_project.gen/sources_1/ip/system_clk_module/system_clk_module.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_clk_module'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/AE_project/FPGA/AE_project/AE_project.gen/sources_1/ip/system_clk_module/system_clk_module_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_clk_module'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
