# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/AE_project/FPGA/AE_project/AE_project.srcs/sources_1/ip/ddr_clk_gen_400M/ddr_clk_gen_400M.xci
# IP: The module: 'ddr_clk_gen_400M' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/AE_project/FPGA/AE_project/AE_project.gen/sources_1/ip/ddr_clk_gen_400M/ddr_clk_gen_400M_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr_clk_gen_400M'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/AE_project/FPGA/AE_project/AE_project.gen/sources_1/ip/ddr_clk_gen_400M/ddr_clk_gen_400M.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr_clk_gen_400M'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/AE_project/FPGA/AE_project/AE_project.gen/sources_1/ip/ddr_clk_gen_400M/ddr_clk_gen_400M_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr_clk_gen_400M'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/AE_project/FPGA/AE_project/AE_project.srcs/sources_1/ip/ddr_clk_gen_400M/ddr_clk_gen_400M.xci
# IP: The module: 'ddr_clk_gen_400M' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/AE_project/FPGA/AE_project/AE_project.gen/sources_1/ip/ddr_clk_gen_400M/ddr_clk_gen_400M_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr_clk_gen_400M'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/AE_project/FPGA/AE_project/AE_project.gen/sources_1/ip/ddr_clk_gen_400M/ddr_clk_gen_400M.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr_clk_gen_400M'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/AE_project/FPGA/AE_project/AE_project.gen/sources_1/ip/ddr_clk_gen_400M/ddr_clk_gen_400M_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr_clk_gen_400M'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
