# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/AE_project/FPGA/AE_project/AE_project.srcs/sources_1/ip/adc_dclk_in/adc_dclk_in.xci
# IP: The module: 'adc_dclk_in' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/AE_project/FPGA/AE_project/AE_project.gen/sources_1/ip/adc_dclk_in/adc_dclk_in_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_dclk_in'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/AE_project/FPGA/AE_project/AE_project.gen/sources_1/ip/adc_dclk_in/adc_dclk_in.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_dclk_in'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/AE_project/FPGA/AE_project/AE_project.gen/sources_1/ip/adc_dclk_in/adc_dclk_in_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_dclk_in'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/AE_project/FPGA/AE_project/AE_project.srcs/sources_1/ip/adc_dclk_in/adc_dclk_in.xci
# IP: The module: 'adc_dclk_in' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/AE_project/FPGA/AE_project/AE_project.gen/sources_1/ip/adc_dclk_in/adc_dclk_in_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_dclk_in'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/AE_project/FPGA/AE_project/AE_project.gen/sources_1/ip/adc_dclk_in/adc_dclk_in.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_dclk_in'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/AE_project/FPGA/AE_project/AE_project.gen/sources_1/ip/adc_dclk_in/adc_dclk_in_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_dclk_in'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
