# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/demo.xdc

# IP: E:/AE_project/FPGA/adc_data_preprocess/adc_data_preprocess.srcs/sources_1/ip/fir_500k_lp/fir_500k_lp.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fir_500k_lp || ORIG_REF_NAME==fir_500k_lp} -quiet] -quiet
