# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/AE_project/FPGA/AE_project/AE_project.srcs/sources_1/ip/ILA_DATA_DOWNSAMPLE/ILA_DATA_DOWNSAMPLE.xci
# IP: The module: 'ILA_DATA_DOWNSAMPLE' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/AE_project/FPGA/AE_project/AE_project.gen/sources_1/ip/ILA_DATA_DOWNSAMPLE/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ILA_DATA_DOWNSAMPLE'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/AE_project/FPGA/AE_project/AE_project.gen/sources_1/ip/ILA_DATA_DOWNSAMPLE/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ILA_DATA_DOWNSAMPLE'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/AE_project/FPGA/AE_project/AE_project.gen/sources_1/ip/ILA_DATA_DOWNSAMPLE/ILA_DATA_DOWNSAMPLE_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ILA_DATA_DOWNSAMPLE'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/AE_project/FPGA/AE_project/AE_project.srcs/sources_1/ip/ILA_DATA_DOWNSAMPLE/ILA_DATA_DOWNSAMPLE.xci
# IP: The module: 'ILA_DATA_DOWNSAMPLE' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/AE_project/FPGA/AE_project/AE_project.gen/sources_1/ip/ILA_DATA_DOWNSAMPLE/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ILA_DATA_DOWNSAMPLE'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/AE_project/FPGA/AE_project/AE_project.gen/sources_1/ip/ILA_DATA_DOWNSAMPLE/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ILA_DATA_DOWNSAMPLE'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/AE_project/FPGA/AE_project/AE_project.gen/sources_1/ip/ILA_DATA_DOWNSAMPLE/ILA_DATA_DOWNSAMPLE_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ILA_DATA_DOWNSAMPLE'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
