# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/AE_project/FPGA/AE_project/AE_project.srcs/sources_1/ip/ILA_AE_AXIS/ILA_AE_AXIS.xci
# IP: The module: 'ILA_AE_AXIS' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/AE_project/FPGA/AE_project/AE_project.gen/sources_1/ip/ILA_AE_AXIS/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ILA_AE_AXIS'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/AE_project/FPGA/AE_project/AE_project.gen/sources_1/ip/ILA_AE_AXIS/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ILA_AE_AXIS'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/AE_project/FPGA/AE_project/AE_project.gen/sources_1/ip/ILA_AE_AXIS/ILA_AE_AXIS_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ILA_AE_AXIS'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/AE_project/FPGA/AE_project/AE_project.srcs/sources_1/ip/ILA_AE_AXIS/ILA_AE_AXIS.xci
# IP: The module: 'ILA_AE_AXIS' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/AE_project/FPGA/AE_project/AE_project.gen/sources_1/ip/ILA_AE_AXIS/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ILA_AE_AXIS'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/AE_project/FPGA/AE_project/AE_project.gen/sources_1/ip/ILA_AE_AXIS/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ILA_AE_AXIS'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/AE_project/FPGA/AE_project/AE_project.gen/sources_1/ip/ILA_AE_AXIS/ILA_AE_AXIS_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ILA_AE_AXIS'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
